## 1.write python code to create array in different ways

In [2]:
import numpy as np

In [2]:
h = np.array([5,6,7,7,8,9])
h

array([5, 6, 7, 7, 8, 9])

In [3]:
list1 = [1,2,3,4,5,6,7]
h1 = np.array(list1)
h1

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
tuple1 = (1,2,3,4,56,7)
h2    = np.array(tuple1)
h2

array([ 1,  2,  3,  4, 56,  7])

## 2.1D numpy array

In [3]:
array1 = np.arange(10,21)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
array2 = np.linspace(0,4,20)
array2

array([0.        , 0.21052632, 0.42105263, 0.63157895, 0.84210526,
       1.05263158, 1.26315789, 1.47368421, 1.68421053, 1.89473684,
       2.10526316, 2.31578947, 2.52631579, 2.73684211, 2.94736842,
       3.15789474, 3.36842105, 3.57894737, 3.78947368, 4.        ])

## 3.find all the attributes of array1 and array2

### array1 attributes

In [14]:
array1.dtype

dtype('int32')

In [15]:
array1.itemsize

4

In [17]:
array1.nbytes

44

In [18]:
array1.size

11

In [19]:
array1.ndim

1

In [21]:
array1.max()

20

In [23]:
array1.min()

10

### array2 attributes

In [24]:
array2.dtype

dtype('float64')

In [25]:
array2.itemsize

8

In [26]:
array2.ndim

1

In [27]:
array2.max()

4.0

In [28]:
array2.min()

0.0

In [29]:
array2.size

20

In [30]:
array2.nbytes

160

## 4.descriptive statistics

### array1

### central tendency

In [ ]:
datatype = int32
structure(rowsxcolumns) = 1x1
missing values = 0
outliers = 0

In [7]:
np.mean(array1)

15.0

In [9]:
np.median(array1)

15.0

In [10]:
array1.max()

20

In [11]:
array1.min()

10

### spread

In [12]:
array1.max() - array1.min() # range

10

In [13]:
q1 = np.percentile(array1,25)
q1

12.5

In [14]:
q3 = np.percentile(array1,75)
q3

17.5

In [16]:
IQR = q3 - q1
IQR

5.0

In [17]:
lower = q1-(1.5*IQR)
lower

5.0

In [18]:
upper = q3+(1.5*IQR)
upper

25.0

In [21]:
np.var(array1) # variance

10.0

In [22]:
np.std(array1)

3.1622776601683795

## array2

### central tendency

In [ ]:
datatype = float64
structure(rowsxcolumns) = 1x1
missing values = 0
outliers = 0

In [5]:
np.mean(array2)

2.0

In [6]:
np.median(array2)

2.0

In [7]:
array2.max()

4.0

In [8]:
array2.min()

0.0

### spread

In [10]:
array2.max() - array2.min()

4.0

In [11]:
q1 = np.percentile(array2,25)
q1

1.0

In [12]:
q3 = np.percentile(array2,75)
q3

3.0

In [13]:
IQR = q3 - q1
IQR

2.0

In [14]:
lower = q1 - (1.5*IQR)
lower

-2.0

In [15]:
upper = q3 + (1.5*IQR)
upper

6.0

In [16]:
np.var(array2)

1.4736842105263157

In [17]:
np.std(array2)

1.2139539573337679