**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



## Creation of ndarray

In [1]:
import numpy as np 

In [15]:
h = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
h

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [16]:
h = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] , ndmin=3)
h

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [17]:
h.reshape(1,3,5)
h

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [18]:
h = np.arange(1,16).reshape(1,3,5)
h

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [15]:
arr1 = np.arange(1,13).reshape(1,1,4,3)
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [5]:
array1 = np.random.rand(20).reshape(1,4,5)
array1

array([[[0.26190223, 0.1103709 , 0.60374439, 0.2947329 , 0.81291919],
        [0.21770169, 0.23248691, 0.1296333 , 0.649257  , 0.77750748],
        [0.26495256, 0.85914009, 0.61618047, 0.36913295, 0.11540439],
        [0.52515048, 0.65877237, 0.37159542, 0.61581333, 0.55690409]]])

In [ ]:
Find all attributes of array1 and array2

In [6]:
array1

array([[[0.26190223, 0.1103709 , 0.60374439, 0.2947329 , 0.81291919],
        [0.21770169, 0.23248691, 0.1296333 , 0.649257  , 0.77750748],
        [0.26495256, 0.85914009, 0.61618047, 0.36913295, 0.11540439],
        [0.52515048, 0.65877237, 0.37159542, 0.61581333, 0.55690409]]])

In [8]:
array1.ndim

3

In [9]:
array1.size

20

In [10]:
array1.itemsize

8

In [11]:
array1.nbytes

160

In [13]:
array1.dtype

dtype('float64')

### Discriptive statistics on arr1

In [16]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [17]:
arr1.min()

1

In [18]:
arr1.max()

12

In [20]:
arr1.mean()

6.5

In [23]:
np.median(arr1)

6.5

In [24]:
np.var(arr1)

11.916666666666666

In [25]:
np.std(arr1)

3.452052529534663

In [30]:
range = arr1.max() - arr1.min()
range

11

In [32]:
q1 = np.percentile(arr1,25)
q1

3.75

In [35]:
q3 = np.percentile(arr1,75)
q3

9.25

In [36]:
IQR = q3 - q1
IQR

5.5

In [39]:
lower = q1 - (1.5*IQR)
lower

-4.5

In [40]:

upper = q3 + (1.5*IQR)
upper

17.5

## Descriptive statistics on array1

In [46]:
array1

array([[[0.26190223, 0.1103709 , 0.60374439, 0.2947329 , 0.81291919],
        [0.21770169, 0.23248691, 0.1296333 , 0.649257  , 0.77750748],
        [0.26495256, 0.85914009, 0.61618047, 0.36913295, 0.11540439],
        [0.52515048, 0.65877237, 0.37159542, 0.61581333, 0.55690409]]])

In [49]:
np.mean(array1)

0.45216510711137736

In [50]:
np.median(array1)

0.4483729516582829

In [52]:
array1.var()

0.05615077033100363

In [53]:
array1.std()

0.23696153766171343

In [54]:
q1 = np.percentile(array1,25)
q1

0.2545483970458178

In [56]:
q3 = np.percentile(array1,75)
q3

0.6244496002297082

In [57]:
IQR = q1 - q3
IQR

-0.3699012031838904

In [58]:
lower = q1 - (1.5*IQR)
lower

0.8094002018216534

In [59]:
upper = q3 + (1.5*IQR)
upper

0.06959779545387257

In [ ]:
*Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - P[rint the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.

In [64]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [67]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
arr1[3]

73

In [70]:
arr2[2][1]

7

In [72]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [73]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [74]:
arr1[1:8]

array([11, 26, 73, 42, 51,  6, 77])

In [ ]:
**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.


In [77]:
h = np.array([1, 2, 3, 4, 5], dtype = "int16")
h

array([1, 2, 3, 4, 5], dtype=int16)

In [78]:
h.dtype

dtype('int16')

In [80]:
h1 =np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype = "float64")

In [81]:
h1.dtype

dtype('float64')

In [82]:
n = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype = "int32")

In [83]:
n.dtype

dtype('int32')

In [84]:
n1 = np.array([1, 2, 3, 4, 5], dtype = "float32")

In [85]:
n1.dtype

dtype('float32')

## Generating Random Numbers

In [88]:
h = np.random.randint(0,101,10)
h

array([27, 75, 35, 71, 50, 77, 72,  4, 63, 88])

In [89]:
np.random.uniform(-1,1,5)

array([ 0.86546791, -0.07968651, -0.29998768,  0.99194532, -0.38599125])

In [90]:
rand_matrix = np.random.randint(50,100,16).reshape(4,4)
rand_matrix

array([[84, 55, 87, 65],
       [54, 70, 57, 68],
       [96, 93, 94, 72],
       [59, 83, 92, 56]])

## Discriptive statistics for rand_matrix

In [91]:
rand_matrix.mean()

74.0625

In [92]:
np.median(rand_matrix)

71.0

In [93]:
rand_matrix.max() - rand_matrix.min()

42

In [95]:
rand_matrix.var()

228.43359375

In [96]:
rand_matrix.std()

15.114019774699251

In [97]:
q1 = np.percentile(rand_matrix,25)

In [98]:
q3 = np.percentile(rand_matrix,75)

In [99]:
IQR = q3 - q1

In [100]:
lower = q1 - (1.5*IQR)
lower


13.875

In [101]:
upper = q3 - (1.5*IQR)
upper

43.625

In [102]:
rand_matrix[rand_matrix < lower]

array([], dtype=int32)

In [103]:
rand_matrix[rand_matrix < upper]

array([], dtype=int32)

In [ ]:
**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?

In [104]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]
)

In [105]:
salaries[salaries<50000]

array([31250, 39828, 41671, 34225, 32199])

### Is it following Normal Distribution


In [107]:
np.median(salaries)

61699.5

In [108]:
salaries.max() - salaries.min() # range

3082388

In [109]:
avg = salaries.mean()
q1 = np.percentile(salaries,25)
q3 = np.percentile(salaries,75)

In [110]:
avg

166169.16666666666

In [111]:
q3

84496.5

In [112]:
q1

52963.25

In [114]:
salaries[salaries<q1]

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

## finding outliers

In [115]:
IQR = q3 - q1
IQR

31533.25

In [116]:
lower = q1 - (1.5*IQR)
lower

5663.375

In [117]:
upper = q3+ (1.5*IQR)
upper

131796.375

In [118]:
salaries[salaries<lower]

array([], dtype=int32)

In [119]:
salaries[salaries>upper] # there is a outlier 

array([3113638])