In [ ]:
1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on  sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [2]:
import numpy as np

In [38]:
h = np.genfromtxt(r"C:\Users\heena\Downloads\Iris_clean_-_Copy.csv" ,dtype="float16",delimiter = ",")
h

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [42]:
sepal_length = h[1:,0:1]
sepal_length

array([[  5.1],
       [  4.9],
       [  4.7],
       [  4.6],
       [ 50. ],
       [  5.4],
       [  4.6],
       [  5. ],
       [  4.4],
       [  4.9],
       [  5.4],
       [  4.8],
       [  4.8],
       [  4.3],
       [  5.8],
       [  5.7],
       [ 50.4],
       [  5.1],
       [  5.7],
       [  5.1],
       [  5.4],
       [  5.1],
       [  4.6],
       [  5.1],
       [  4.8],
       [  5. ],
       [  5. ],
       [  5.2],
       [  5.2],
       [  4.7],
       [  4.8],
       [  5.4],
       [  5.2],
       [  5.5],
       [  4.9],
       [  5. ],
       [  5.5],
       [  4.9],
       [  4.4],
       [  5.1],
       [  5. ],
       [  4.5],
       [  4.4],
       [  5. ],
       [  5.1],
       [  4.8],
       [  5.1],
       [  4.6],
       [  5.3],
       [  5. ],
       [  7. ],
       [  6.4],
       [  6.9],
       [  5.5],
       [  6.5],
       [  5.7],
       [116.3],
       [  4.9],
       [  6.6],
       [  5.2],
       [  5. ],
       [  5.9],
       [

In [43]:
np.where(sepal_length>10) # outliers

(array([  4,  16,  56, 129], dtype=int64), array([0, 0, 0, 0], dtype=int64))

In [45]:
sepal_length = np.where(sepal_length>10,np.nanmedian(sepal_length),sepal_length) 
sepal_length

array([[5.1],
       [4.9],
       [4.7],
       [4.6],
       [5.8],
       [5.4],
       [4.6],
       [5. ],
       [4.4],
       [4.9],
       [5.4],
       [4.8],
       [4.8],
       [4.3],
       [5.8],
       [5.7],
       [5.8],
       [5.1],
       [5.7],
       [5.1],
       [5.4],
       [5.1],
       [4.6],
       [5.1],
       [4.8],
       [5. ],
       [5. ],
       [5.2],
       [5.2],
       [4.7],
       [4.8],
       [5.4],
       [5.2],
       [5.5],
       [4.9],
       [5. ],
       [5.5],
       [4.9],
       [4.4],
       [5.1],
       [5. ],
       [4.5],
       [4.4],
       [5. ],
       [5.1],
       [4.8],
       [5.1],
       [4.6],
       [5.3],
       [5. ],
       [7. ],
       [6.4],
       [6.9],
       [5.5],
       [6.5],
       [5.7],
       [5.8],
       [4.9],
       [6.6],
       [5.2],
       [5. ],
       [5.9],
       [6. ],
       [6.1],
       [5.6],
       [6.7],
       [5.6],
       [5.8],
       [6.2],
       [5.6],
       [5.9],
      

In [46]:
sepal_length = np.where(np.isnan(sepal_length),np.nanmean(sepal_length),sepal_length)
sepal_length

array([[5.1 ],
       [4.9 ],
       [4.7 ],
       [4.6 ],
       [5.8 ],
       [5.4 ],
       [4.6 ],
       [5.  ],
       [4.4 ],
       [4.9 ],
       [5.4 ],
       [4.8 ],
       [4.8 ],
       [4.3 ],
       [5.8 ],
       [5.7 ],
       [5.8 ],
       [5.1 ],
       [5.7 ],
       [5.1 ],
       [5.4 ],
       [5.1 ],
       [4.6 ],
       [5.1 ],
       [4.8 ],
       [5.  ],
       [5.  ],
       [5.2 ],
       [5.2 ],
       [4.7 ],
       [4.8 ],
       [5.4 ],
       [5.2 ],
       [5.5 ],
       [4.9 ],
       [5.  ],
       [5.5 ],
       [4.9 ],
       [4.4 ],
       [5.1 ],
       [5.  ],
       [4.5 ],
       [4.4 ],
       [5.  ],
       [5.1 ],
       [4.8 ],
       [5.1 ],
       [4.6 ],
       [5.3 ],
       [5.  ],
       [7.  ],
       [6.4 ],
       [6.9 ],
       [5.5 ],
       [6.5 ],
       [5.7 ],
       [5.8 ],
       [4.9 ],
       [6.6 ],
       [5.2 ],
       [5.  ],
       [5.9 ],
       [6.  ],
       [6.1 ],
       [5.6 ],
       [6.7 ],
       [5.

In [48]:
sepal_width = h[1:,1:2]
sepal_width

array([[  3.5],
       [  3. ],
       [  3.2],
       [  3.1],
       [  3.6],
       [  nan],
       [  3.4],
       [  3.4],
       [  2.9],
       [  3.1],
       [  3.7],
       [  3.4],
       [130. ],
       [  3. ],
       [  4. ],
       [  4.4],
       [  nan],
       [  3.5],
       [  3.8],
       [  3.8],
       [  3.4],
       [  3.7],
       [  3.6],
       [  3.3],
       [  3.4],
       [  3. ],
       [ 34. ],
       [  3.5],
       [  3.4],
       [  3.2],
       [  3.1],
       [  3.4],
       [  4.1],
       [  4.2],
       [  3.1],
       [  3.2],
       [  3.5],
       [  3.1],
       [  3. ],
       [  3.4],
       [  3.5],
       [  2.3],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3. ],
       [  3.8],
       [  3.2],
       [  3.7],
       [  3.3],
       [  3.2],
       [  3.2],
       [  nan],
       [  2.3],
       [  2.8],
       [  2.8],
       [  3.3],
       [  2.4],
       [  2.9],
       [  2.7],
       [  2. ],
       [  3. ],
       [

In [49]:
np.where(sepal_width>5)

(array([12, 26, 92], dtype=int64), array([0, 0, 0], dtype=int64))

In [51]:
sepal_width = np.where(sepal_width>5,np.nanmedian(sepal_width),sepal_width)
sepal_width

array([[3.5],
       [3. ],
       [3.2],
       [3.1],
       [3.6],
       [nan],
       [3.4],
       [3.4],
       [2.9],
       [3.1],
       [3.7],
       [3.4],
       [3. ],
       [3. ],
       [4. ],
       [4.4],
       [nan],
       [3.5],
       [3.8],
       [3.8],
       [3.4],
       [3.7],
       [3.6],
       [3.3],
       [3.4],
       [3. ],
       [3. ],
       [3.5],
       [3.4],
       [3.2],
       [3.1],
       [3.4],
       [4.1],
       [4.2],
       [3.1],
       [3.2],
       [3.5],
       [3.1],
       [3. ],
       [3.4],
       [3.5],
       [2.3],
       [3.2],
       [3.5],
       [3.8],
       [3. ],
       [3.8],
       [3.2],
       [3.7],
       [3.3],
       [3.2],
       [3.2],
       [nan],
       [2.3],
       [2.8],
       [2.8],
       [3.3],
       [2.4],
       [2.9],
       [2.7],
       [2. ],
       [3. ],
       [2.2],
       [2.9],
       [2.9],
       [3.1],
       [3. ],
       [2.7],
       [2.2],
       [2.5],
       [3.2],
      

In [52]:
sepal_width = np.where(np.isnan(sepal_width),np.nanmean(sepal_width),sepal_width)
sepal_width                      

array([[3.5 ],
       [3.  ],
       [3.2 ],
       [3.1 ],
       [3.6 ],
       [3.03],
       [3.4 ],
       [3.4 ],
       [2.9 ],
       [3.1 ],
       [3.7 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [4.  ],
       [4.4 ],
       [3.03],
       [3.5 ],
       [3.8 ],
       [3.8 ],
       [3.4 ],
       [3.7 ],
       [3.6 ],
       [3.3 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [3.5 ],
       [3.4 ],
       [3.2 ],
       [3.1 ],
       [3.4 ],
       [4.1 ],
       [4.2 ],
       [3.1 ],
       [3.2 ],
       [3.5 ],
       [3.1 ],
       [3.  ],
       [3.4 ],
       [3.5 ],
       [2.3 ],
       [3.2 ],
       [3.5 ],
       [3.8 ],
       [3.  ],
       [3.8 ],
       [3.2 ],
       [3.7 ],
       [3.3 ],
       [3.2 ],
       [3.2 ],
       [3.03],
       [2.3 ],
       [2.8 ],
       [2.8 ],
       [3.3 ],
       [2.4 ],
       [2.9 ],
       [2.7 ],
       [2.  ],
       [3.  ],
       [2.2 ],
       [2.9 ],
       [2.9 ],
       [3.1 ],
       [3.

In [54]:
petal_length = h[1:,2:3]
petal_length

array([[ 1.4],
       [ 1.4],
       [ 1.3],
       [ 1.5],
       [ 1.4],
       [ 1.7],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ nan],
       [ 1.5],
       [ 1.6],
       [ 1.4],
       [ 1.1],
       [ 1.2],
       [ 1.5],
       [ 1.3],
       [ 1.4],
       [ 1.7],
       [ 1.5],
       [ 1.7],
       [ 1.5],
       [ 1. ],
       [ 1.7],
       [ 1.9],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.4],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.5],
       [ 1.4],
       [ 1.5],
       [ 1.2],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [13. ],
       [ 1.3],
       [ 1.6],
       [ 1.9],
       [ 1.4],
       [ 1.6],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 4.7],
       [ 4.5],
       [ 4.9],
       [ 4. ],
       [ 4.6],
       [ 4.5],
       [ 4.7],
       [ 3.3],
       [ 4.6],
       [ 3.9],
       [ 3.5],
       [ 4.2],
       [ 4. ],
       [ 4.7],
       [ 3.6],
       [ 4.4],
       [ 4

In [55]:
np.where(petal_length>10)

(array([41, 80], dtype=int64), array([0, 0], dtype=int64))

In [56]:
petal_length = np.where(petal_length>10,np.nanmedian(petal_length),petal_length)
petal_length

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.5],
       [1.4],
       [nan],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [4.5],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
      

In [57]:
petal_length = np.where(np.isnan(petal_length),np.nanmean(petal_length),petal_length)
petal_length

array([[1.4  ],
       [1.4  ],
       [1.3  ],
       [1.5  ],
       [1.4  ],
       [1.7  ],
       [1.4  ],
       [1.5  ],
       [1.4  ],
       [3.912],
       [1.5  ],
       [1.6  ],
       [1.4  ],
       [1.1  ],
       [1.2  ],
       [1.5  ],
       [1.3  ],
       [1.4  ],
       [1.7  ],
       [1.5  ],
       [1.7  ],
       [1.5  ],
       [1.   ],
       [1.7  ],
       [1.9  ],
       [1.6  ],
       [1.6  ],
       [1.5  ],
       [1.4  ],
       [1.6  ],
       [1.6  ],
       [1.5  ],
       [1.5  ],
       [1.4  ],
       [1.5  ],
       [1.2  ],
       [1.3  ],
       [1.5  ],
       [1.3  ],
       [1.5  ],
       [1.3  ],
       [4.5  ],
       [1.3  ],
       [1.6  ],
       [1.9  ],
       [1.4  ],
       [1.6  ],
       [1.4  ],
       [1.5  ],
       [1.4  ],
       [4.7  ],
       [4.5  ],
       [4.9  ],
       [4.   ],
       [4.6  ],
       [4.5  ],
       [4.7  ],
       [3.3  ],
       [4.6  ],
       [3.9  ],
       [3.5  ],
       [4.2  ],
       [

In [60]:
petal_width = h[1:,3:]
petal_width

array([[2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [1.020e+01],
       [2.000e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [1.010e+01],
       [9.998e-02],
       [2.000e-01],
       [3.999e-01],
       [3.999e-01],
       [3.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [5.000e-01],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [1.102e+02],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [9.998e-02],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [6.001e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],


In [61]:
np.where(petal_width>3)

(array([ 3, 12, 28, 57, 98], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64))

In [62]:
petal_width =  np.where(petal_width>3,np.nanmedian(petal_width),petal_width)
petal_width

array([[0.2],
       [0.2],
       [0.2],
       [1.5],
       [0.2],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [1.5],
       [0.1],
       [0.2],
       [0.4],
       [0.4],
       [0.3],
       [0.3],
       [0.3],
       [0.2],
       [0.4],
       [0.2],
       [0.5],
       [0.2],
       [0.2],
       [0.4],
       [0.2],
       [1.5],
       [0.2],
       [0.2],
       [0.4],
       [0.1],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.3],
       [0.3],
       [0.2],
       [0.6],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [1.4],
       [1.5],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.6],
       [1.5],
       [1.3],
       [1.4],
       [1. ],
       [1.5],
       [1. ],
       [1.4],
       [1.3],
       [1.4],
       [1.5],
       [1. ],
       [1.5],
       [1.1],
       [1.8],
      

In [ ]:
2. What is the mean value of sepal length

In [63]:
np.mean(sepal_length)

5.87

In [35]:
3.sort the sepal width in ascending order.



In [64]:
np.sort(sepal_width)

array([[3.5 ],
       [3.  ],
       [3.2 ],
       [3.1 ],
       [3.6 ],
       [3.03],
       [3.4 ],
       [3.4 ],
       [2.9 ],
       [3.1 ],
       [3.7 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [4.  ],
       [4.4 ],
       [3.03],
       [3.5 ],
       [3.8 ],
       [3.8 ],
       [3.4 ],
       [3.7 ],
       [3.6 ],
       [3.3 ],
       [3.4 ],
       [3.  ],
       [3.  ],
       [3.5 ],
       [3.4 ],
       [3.2 ],
       [3.1 ],
       [3.4 ],
       [4.1 ],
       [4.2 ],
       [3.1 ],
       [3.2 ],
       [3.5 ],
       [3.1 ],
       [3.  ],
       [3.4 ],
       [3.5 ],
       [2.3 ],
       [3.2 ],
       [3.5 ],
       [3.8 ],
       [3.  ],
       [3.8 ],
       [3.2 ],
       [3.7 ],
       [3.3 ],
       [3.2 ],
       [3.2 ],
       [3.03],
       [2.3 ],
       [2.8 ],
       [2.8 ],
       [3.3 ],
       [2.4 ],
       [2.9 ],
       [2.7 ],
       [2.  ],
       [3.  ],
       [2.2 ],
       [2.9 ],
       [2.9 ],
       [3.1 ],
       [3.

In [ ]:
4.apply all statistical measures on sepal width and length

In [65]:
np.mean(sepal_width)

3.03

In [66]:
np.mean(sepal_length)

5.87

In [68]:
np.median(sepal_length)

5.8

In [69]:
np.median(sepal_width)

3.0

In [70]:
np.std(sepal_width)

0.4104

In [71]:
np.std(sepal_length)

0.808

In [73]:
q1 = np.quantile(sepal_length,0.25)
q1

5.19921875

In [74]:
q3 = np.quantile(sepal_length,0.75)
q3

6.3984375

In [77]:
IQR = q3 - q1
IQR

1.19921875

In [78]:
q1 = np.quantile(sepal_width,0.25)
q1

2.80078125

In [79]:
q3 = np.quantile(sepal_width,0.75)
q3

3.19921875

In [81]:
IQR = q3 - q1
IQR

0.3984375

In [82]:
range1 = np.max(sepal_width) - np.min(sepal_width)

In [83]:
range1

2.398

In [85]:
range2 = np.max(sepal_length) - np.min(sepal_length)
range2

3.398

In [ ]:
after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [86]:
np.savetxt("sepal_length_cleaned_iris.txt",sepal_length)

In [87]:
np.loadtxt("sepal_length_cleaned_iris.txt")

array([5.1015625 , 4.8984375 , 4.69921875, 4.6015625 , 5.80078125,
       5.3984375 , 4.6015625 , 5.        , 4.3984375 , 4.8984375 ,
       5.3984375 , 4.80078125, 4.80078125, 4.30078125, 5.80078125,
       5.69921875, 5.80078125, 5.1015625 , 5.69921875, 5.1015625 ,
       5.3984375 , 5.1015625 , 4.6015625 , 5.1015625 , 4.80078125,
       5.        , 5.        , 5.19921875, 5.19921875, 4.69921875,
       4.80078125, 5.3984375 , 5.19921875, 5.5       , 4.8984375 ,
       5.        , 5.5       , 4.8984375 , 4.3984375 , 5.1015625 ,
       5.        , 4.5       , 4.3984375 , 5.        , 5.1015625 ,
       4.80078125, 5.1015625 , 4.6015625 , 5.30078125, 5.        ,
       7.        , 6.3984375 , 6.8984375 , 5.5       , 6.5       ,
       5.69921875, 5.80078125, 4.8984375 , 6.6015625 , 5.19921875,
       5.        , 5.8984375 , 6.        , 6.1015625 , 5.6015625 ,
       6.69921875, 5.6015625 , 5.80078125, 6.19921875, 5.6015625 ,
       5.8984375 , 6.1015625 , 6.30078125, 6.1015625 , 6.39843

In [88]:
np.savetxt("sepal_width_cleaned_iris.txt",sepal_width)

In [89]:
np.loadtxt("sepal_width_cleaned_iris.txt")

array([3.5       , 3.        , 3.19921875, 3.09960938, 3.59960938,
       3.02929688, 3.40039062, 3.40039062, 2.90039062, 3.09960938,
       3.69921875, 3.40039062, 3.        , 3.        , 4.        ,
       4.3984375 , 3.02929688, 3.5       , 3.80078125, 3.80078125,
       3.40039062, 3.69921875, 3.59960938, 3.30078125, 3.40039062,
       3.        , 3.        , 3.5       , 3.40039062, 3.19921875,
       3.09960938, 3.40039062, 4.1015625 , 4.19921875, 3.09960938,
       3.19921875, 3.5       , 3.09960938, 3.        , 3.40039062,
       3.5       , 2.30078125, 3.19921875, 3.5       , 3.80078125,
       3.        , 3.80078125, 3.19921875, 3.69921875, 3.30078125,
       3.19921875, 3.19921875, 3.02929688, 2.30078125, 2.80078125,
       2.80078125, 3.30078125, 2.40039062, 2.90039062, 2.69921875,
       2.        , 3.        , 2.19921875, 2.90039062, 2.90039062,
       3.09960938, 3.        , 2.69921875, 2.19921875, 2.5       ,
       3.19921875, 2.80078125, 2.5       , 3.02929688, 2.90039

In [90]:
np.savetxt("petal_width_cleaned_iris.txt",petal_width)

In [91]:
np.loadtxt("petal_width_cleaned_iris.txt")

array([0.19995117, 0.19995117, 0.19995117, 1.5       , 0.19995117,
       0.39990234, 0.30004883, 0.19995117, 0.19995117, 0.09997559,
       0.19995117, 0.19995117, 1.5       , 0.09997559, 0.19995117,
       0.39990234, 0.39990234, 0.30004883, 0.30004883, 0.30004883,
       0.19995117, 0.39990234, 0.19995117, 0.5       , 0.19995117,
       0.19995117, 0.39990234, 0.19995117, 1.5       , 0.19995117,
       0.19995117, 0.39990234, 0.09997559, 0.19995117, 0.09997559,
       0.19995117, 0.19995117, 0.09997559, 0.19995117, 0.19995117,
       0.30004883, 0.30004883, 0.19995117, 0.60009766, 0.39990234,
       0.30004883, 0.19995117, 0.19995117, 0.19995117, 0.19995117,
       1.40039062, 1.5       , 1.5       , 1.29980469, 1.5       ,
       1.29980469, 1.59960938, 1.5       , 1.29980469, 1.40039062,
       1.        , 1.5       , 1.        , 1.40039062, 1.29980469,
       1.40039062, 1.5       , 1.        , 1.5       , 1.09960938,
       1.79980469, 1.29980469, 1.5       , 1.20019531, 1.29980